# .github/workflows/deploy.yml

name: Deploy BigBasket Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'   # change if you use different Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Trigger Render Deployment
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
